### ISSUE TITLE
 Warning message does not support Ansible version 2.14.6

### ISSUE THREAD

**Issue by gilbert-hsu** [prometheus-community/ansible#144]
still get warning message in ansible 2.14.6

```
$ ansible-playbook --inventory inventory
TASK [include roles] **************************************************************************
[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.14.6
```

in https://github.com/prometheus-community/ansible/blob/main/meta/runtime.yml#L2 
the supported ansible version is 2.9.0*, 2.10.0*, 2.11.0*, 2.12.0*, 2.13.0*, 2.14.0*, 2.15.0*

would it be ">= 2.9.0,  < 2.16.0" ？

**Comment by gardar** [comment]
Already noted, will be fixed with #117

**Comment by theunkn0wn1** [comment]
Issue persists with version 0.6.0 from galaxy, and 0.7.0 installed from git.

**Comment by Mickey-ts** [comment]
Any update or workaround for this?

**Comment by thibaultamartin** [comment]
It looks like the [version 0.7.0 if this collection was released](https://github.com/prometheus-community/ansible/releases/tag/0.7.0) but [didn't make it to ansible-galaxy](https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/)

**Comment by gardar** [comment]
> Any update or workaround for this?

A workaround is not really required as this is just a warning message and won't affect anything. Unless you have changed the default setting from a warning to a error.
In that case you can change it back to a warning or even just ignore it completely by turning it off.
See: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-on-ansible-version-mismatch

> It looks like the [version 0.7.0 if this collection was released](https://github.com/prometheus-community/ansible/releases/tag/0.7.0) but [didn't make it to ansible-galaxy](https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/)

Yes we've had some issues with publishing the version after ansible galaxy was updated last month, hopefully this can be fixed soon.
