### ISSUE TITLE
[prometheus] - New scrape_config_files

### ISSUE THREAD

**Issue by Birckof** [prometheus-community/ansible#145]
Starting from version 2.43.0 of Prometheus, we have a new section available in the configuration file prometheus.yml called 'scrape_config_files,' where you can specify the paths of files containing the scrape_config settings. 

Would it be possible to implement this functionality by adding the 'scrape_config_files' attribute to the prometheus.yml.j2 template if it is defined in a variable, for example, 'prometheus_scrape_config_files'? It could be a list of paths."

**Comment by SuperQ** [comment]
Yes, that should be easy enough to add. PRs welcome.
