### ISSUE TITLE
Question: What is the galaxy name of this roles/collections?

### ISSUE THREAD

**Issue by kaufmo** [prometheus-community/ansible#18]
Hi sry for that question I'm totally new in the ansible world.

I'm migration from cloudalchemy and I'm wondering where do I find these roles in galaxy what is the name for them? I use prometheus and node_exporter.

Thx for the help and sry for that questions :sweat_smile:

**Comment by Nereis** [comment]
Same question here. Communication about the migration from cloudalchemy.node_exporter is a bit messy. No indication on the readme of cloudalchemy, you have to dig in the tickets. The readme in the node_exporter role of this repository is still pointing on the old cloudalchemy collection in 2.0.0.

In the meantime, web.config option is not working with latest version of the latest node_exporter release

Please help ❤

**Comment by Nereis** [comment]
I tried to install directly the repository 
`ansible-galaxy collection install git+https://github.com/prometheus-community/ansible.git`
Apparently it loads only the role for prometheus. I wasn't able to get the role for the node_exporter.

**Comment by gardar** [comment]
This collection is still WIP, so it hasn't been published on galaxy and hasn't been advertised as a replacement for the cloudalchemy roles yet.

**Comment by kaufmo** [comment]
> This collection is still WIP, so it hasn't been published on galaxy and hasn't been advertised as a replacement for the cloudalchemy roles yet.

is there any time plan when this will be ready, it would be really cool thx :+1:

**Comment by chriscarpenter12** [comment]
This migration to this repo is extremely confusing.

**Comment by andygrunwald** [comment]
FYI: The https://github.com/cloudalchemy/ansible-node-exporter repository has been archived since Mar 2, 2023.
This repository (https://github.com/prometheus-community/ansible) is marked as the successor:
> This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.

**Comment by SuperQ** [comment]
Yes, sorry for the delay in getting this stuff migrated. We've got some of the core roles done. There are still other roles we need to migrate, but the collection is now published on Ansible galaxy.

Here is a basic playbook entry:

```yaml
- name: Deploy node_exporter
  hosts: all
  collections:
    - prometheus.prometheus
  roles:
  - prometheus.prometheus.node_exporter
  tags:
  - node_exporter
```
