### ISSUE TITLE
consider not modifying the node exporter user if it already exists

### ISSUE THREAD

**Issue by bluppfisk** [prometheus-community/ansible#183]
Using the node_exporter role without fully checking all the steps (mea culpa), I was astonished to find out that it had reduced the user I wanted to run node-exporter as to a no-login, no-home, system user. This then caused other issues with other services running under this user's name and that very much expect to have a home directory of their own.

I think the role should check whether the user already exists and not modify the user if so.

The service file should then also not include `ProtectHome=yes` as this would effectively disable it from accessing its own home, where, in my case all the metrics prom files are written to.

**Comment by SuperQ** [comment]
No, we want our Ansible roles to be idempotent. We need to maintain all configurations in order for this policy to be maintained.

`ProtectHome` is a different issue, we can add a check like we do for mounts to not enable `ProtectHome` if the textfile path contains `/home`.

**Comment by bluppfisk** [comment]
I'll still need to use a fork for my own purposes, but I understand that this may not work for all. The latter part is a sweet and rapid improvement :) cheers
