### ISSUE TITLE
unable to run node_exporter playbook when offline and SELinux enabled on RedHat

### ISSUE THREAD

**Issue by avdland** [prometheus-community/ansible#225]
**Background:**
We are using RedHat with SELinux enabled in an offline environment.
When SELinux is enabled, the node_exporter playbook wants to make sure two packages are present: python3-libselinux and python3-policycoreutils.
**Problem:**
The task to check for the presence of the packages always fails due to Yum which is unable to fetch metadata from the Yum repositories. Note that the packages are already installed so why does Yum wants to fetch repo metadata.

I've noticed that when I run "yum check-update" beforehand with internet temporarily enabled, the task does succeed afterwards when offline...

**Comment by gardar** [comment]
While I agree that this is [a bug in the ansible module](https://github.com/ansible/ansible/issues/81847) I don't think that this is something we should account for, it feels strange to have a host in a air gapped/offline environment but still have yum/dnf configured to use public mirrors.

In this situation I would set up a internal yum mirror, but if that's out of the question then you could even set up a local directory mirror for yum that's on the host itself.
