### ISSUE TITLE
Skip installation of binaries

### ISSUE THREAD

**Issue by wagneradrian92** [prometheus-community/ansible#321]
Hello everyone, i was wondering if there was a way to skip the download and installation of the diffrent binaries (e.g. node_exporter, blackbox_exporter etc.) If the binary is already running on the version defined in the config? 
Example: 
Node_exporter_version: 1.7.0
Skip install: true if version set via variable is already installes
Thanks
Regards
Adrian

**Comment by QCU87Z** [comment]
Are you talking about something like this?
https://github.com/prometheus-community/ansible/blob/4e881c667d65eb0110b97c815aa9feb13a845f2f/roles/prometheus/tasks/install.yml#L41

Where you can pass an extra var on the command line like
`ansible-playbook ... -e prometheus_skip_install=true`

That works for me with the prometheus role. Found by looking in the install.yml task

**Comment by gardar** [comment]
You can use tags to skip either the install or the download.

You can use `--skip-tags install` or `--skip-tags download` to skip the install or download tasks across all the roles (if you run multiple roles in your playbook).
If you only want to skip the download or install for specific roles you can use `--skip-tags <role_name>_install` or `--skip-tags <role_name>_download`. For example: `--skip-tags blackbox_exporter_install,node_exporter_install` etc.

**Comment by SuperQ** [comment]
PRs welcome.
