### ISSUE TITLE
Documentation release version mismatch

### ISSUE THREAD

**Issue by manzsolutions-lpr** [prometheus-community/ansible#370]
The version mentioned in the [official documentation](https://prometheus-community.github.io/ansible/branch/main/) is 0.16.4 but the latest release/tag on Github is 0.16.3 which is also listed on [Ansible Galaxy](https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/). Was 0.16.4 perhaps meant to be released but got stuck in the process?

**Comment by gardar** [comment]
You are looking at the docs for the main branch, the main branch contains the latest (unreleased/upcoming) changes

**Comment by manzsolutions-lpr** [comment]
Yes, but it's also what the link on Ansible Galaxy redirects to: https://prometheus-community.github.io/ansible/

**Comment by gardar** [comment]
Ah, good point, I'll try to get that changed.
