### ISSUE TITLE
[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.17.0

### ISSUE THREAD

**Issue by andygrunwald** [prometheus-community/ansible#386]
During an ansible run, the following warning will be thrown:

```
[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.17.0
```

Right now, the runtime information limits it to `2.16.*`:

https://github.com/prometheus-community/ansible/blob/f0030673774193349a3f8b9956d6361fad688cb7/meta/runtime.yml#L2

Do you have any special check/test-suite you run before you enable this collection to work with a new Ansible version?
Otherwise, I can create a PR to support Ansible 2.17.*.
In my setup, it works pretty well so far.

## `requirements.yml`

```yml
collections:
  - name: prometheus.prometheus
    version: 0.16.3
```

## Ansible Version

```sh
$ ansible --version
ansible [core 2.17.0]
  config file = None
  configured module search path = ['/Users/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.0.1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.0.1/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

**Comment by pablolanchez** [comment]
I am having the same issue but with version 2.17.1

[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.17.1

**Comment by pmiriyev** [comment]
same here:

[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.17.3

**Comment by andygrunwald** [comment]
FYI: https://github.com/prometheus-community/ansible/pull/414
