### ISSUE TITLE
When will 0.17.0 be released?

### ISSUE THREAD

**Issue by bossm8** [prometheus-community/ansible#393]
The documentation on [GitHub Pages](https://prometheus-community.github.io/ansible/branch/main/) documents version 0.17.0 which contains features we could already use. However, the releases on ansible are still on 0.16.3 ([galaxy](https://galaxy.ansible.com/ui/repo/published/prometheus/prometheus/)). Do you have a date when 0.17.0 will be released?

**Comment by SuperQ** [comment]
Thanks for the reminder, it looks like we had a bunch of stuff stacked up waiting for the release button.
