### ISSUE TITLE
prometheus_scrape_config_files variable incorrect?

### ISSUE THREAD

**Issue by MattiasSkohg** [prometheus-community/ansible#406]
Hi,

New to Prometheus but i have begun deploying prometheus through ansible, i noticed that i had issues when restarting the prometheus service, due to a file being configured which i dont believe should.

After some poking around i noticed that the default value from the prometheus role according to the documentation should be:

```
prometheus_scrape_config_files
Default: ["prometheus/scrapes/*.yml", "prometheus/scrapes/*.json"]
```

However, looking in the code, (prometheus/roles/prometheus/defaults/main.yml) its actually set to the same as the targets variable which seems incorrect?

```
["prometheus/targets/*.yml", "prometheus/targets/*.json"]
```

As i workaround i have simply declared prometheus_scrape_config_files="prometheus/scrapes/*.yml", "prometheus/scrapes/*.json" in the vars file.

**Comment by manzsolutions-lpr** [comment]
Well I missed that when initially appropriating an abandoned PR but immediately fixed it in a second PR. Unfortunately it hit a couple of obstacles and has been unable to proceed for issues with the CI unrelated to PR itself for months now: https://github.com/prometheus-community/ansible/pull/377

I guess once #411 gets merged it may finally complete all CI jobs.

**Comment by gardar** [comment]
#377
