### ISSUE TITLE
node_exporter role objc crashing after fork() call

### ISSUE THREAD

**Issue by brko7** [prometheus-community/ansible#419]
`TASK [prometheus.prometheus.node_exporter : Get checksum list from github] *************************************************
objc[77078]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[77078]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state`

When running from MacOS, the role is crashing.

This can be fixed by setting the env variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`, but I am not sure if this is intended or not.

**Comment by gardar** [comment]
This is a ansible / mac os issue, see the ansible docs https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#running-on-macos-as-a-control-node
