### ISSUE TITLE
_common role change breaks user updates

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/ansible#426]
When switching to the new common role, I end up with failed updates due to the user changes.

```
TASK [prometheus.prometheus._common : Create system user blackbox-exp] *********
fatal: [demo]: FAILED! => {"changed": false, "msg": "usermod: user blackbox-exp is currently used by process 401245\n", "name": "blackbox-exp", "rc": 8}
```

**Comment by gardar** [comment]
Hmm, I wonder what's causing that, can you check the verbose output? I'm wondering if the old user had a different home directory or shell, there were some inconsistencies between the roles for those.
