### ISSUE TITLE
Create localhost binary cache path failing on AWX.

### ISSUE THREAD

**Issue by shammahalchemy** [prometheus-community/ansible#427]
Hi there!

Using AWX 21.5.0, awx-operator, and ansible [core 2.15.12]

I'm now getting the following error since the release of 0.20.0 while running our playbook under check mode.
```
TASK [prometheus.prometheus._common : Create localhost binary cache path] ****** 
fatal: [snip -> localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: sudo: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
fatal: [snip -> localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: sudo: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
```

I've temporarily pinned our version to 0.19.0.

Thanks for looking into this!

**Comment by gardar** [comment]
Looks like it's attempting to run that task with elevated privileges, which should not happen, are you by any chance applying "become" to the role your playbook?

**Comment by Davenchy** [comment]
> Looks like it's attempting to run that task with elevated privileges, which should not happen, are you by any chance applying "become" to the role your playbook?

Yeah, I had the same issue, but it worked after I removed `become`.
Thanks
