### ISSUE TITLE
Missing directories must be created for cache path when running in check mode

### ISSUE THREAD

**Issue by erikgb** [prometheus-community/ansible#430]
Running the latest release (0.20.1) in check mode no longer works. I think a bug snuck into https://github.com/prometheus-community/ansible/commit/8734f607dbfc1504cfa592bafb89f5740d0ee7ac. The download tasks are configured to always run (on Ansible controller), and they are always failing in our container-based Ansible controller setup.

````
fatal: [<REDACTED> -> localhost]: FAILED! => changed=false 
  attempts: 5
  checksum_dest: null
  checksum_src: 95ff3258ce71954668c4cc75f162951c877f0fb0
  dest: /tmp/blackbox_exporter-linux-amd64/0.25.0/blackbox_exporter-0.25.0.linux-amd64.tar.gz
  elapsed: 1
  msg: Destination /tmp/blackbox_exporter-linux-amd64/0.25.0 does not exist
  src: /home/ansible/.ansible/tmp/ansible-tmp-1729250055.4059544-284-113531158180570/tmpg82m8jdq
  url: https://<REDACTED>/github/prometheus/blackbox_exporter/releases/download/v0.25.0/blackbox_exporter-0.25.0.linux-amd64.tar.gz
````

There seems to be missing a task to create eventual missing directories in the cache path (on Ansible controller). I have already patched the Ansible collection locally and will submit a PR to fix this.

**Comment by gardar** [comment]
You could also use `--skip-tags download` which would skip the download tasks, then you can provide the binaries in a directory of your choosing by overriding the `blackbox_exporter_local_cache_path`.

**Comment by erikgb** [comment]
But where should I get the binaries from? Download them manually? We install several components from this collection, and there seems to be no shared default for the roles cache download dir. This means I have to download X files and set X variables. I rather wait for a patch release and run with my local bugfix for now. 😄

**Comment by gardar** [comment]
> But where should I get the binaries from? Download them manually? We install several components from this collection, and there seems to be no shared default for the roles cache download dir. This means I have to download X files and set X variables. I rather wait for a patch release and run with my local bugfix for now. 😄

Yeah that option exists if you wish to BYOB (bring your own ~~beer~~ binaries 😄). Which you could populate somehow, for example with `pre_tasks` in your playbook.
