### ISSUE TITLE
"only prometheus 2.x is supported" for `prometheus_version`

### ISSUE THREAD

**Issue by dmke** [prometheus-community/ansible#460]
Does this note only exists to discourage user to install Prometheus 1.x with the `prometheus.prometheus.prometheus` role, or is it actually not possible to install Prometheus 3.0 with it?

> ![image](https://github.com/user-attachments/assets/e44dccf4-034f-414c-89a8-5efe146372b9)
> 
> https://prometheus-community.github.io/ansible/branch/main/prometheus_role.html

I'm hesitant to try this on my production machine, in case something unexpected breaks, hence this request for clarification.

**Comment by SuperQ** [comment]
Yes, this was originally to discourage Prometheus 1.x.

I don't think there are any issues with 3.x, but we haven't explicitly tested it yet.

**Comment by dmke** [comment]
OK, thanks. I'll later setup a test machine, try to deploy 3.x to it, and report back.
