### ISSUE TITLE
Issues with templating of systemd unit config files 

### ISSUE THREAD

**Issue by alkinks** [prometheus-community/ansible#68]
I'm seeing this issue when trying to exclude filesystem types from the filesystem collector of the node_exporter.

I'm using a variable like this:
```yaml
node_exporter_enabled_collectors:
- filesystem:
      fs-types-exclude: ^(nfs|autofs)$
```

Which results in this in node_exporter.service:
```
ExecStart=/usr/local/bin/node_exporter \
--collector.filesystem \
    --collector.filesystem.fs-types-exclude='^(nfs|autofs)$' \
```
And - I see this in the logs:
`caller=filesystem_common.go:113 level=info collector=filesystem msg="Parsed flag --collector.filesystem.fs-types-exclude" flag='^(nfs|autofs)$'`

And these are some of the metrics scraped from the exporter
```
node_filesystem_size_bytes{device="auto.job",fstype="autofs",mountpoint="/job"} 0
node_filesystem_size_bytes{device="auto.net",fstype="autofs",mountpoint="/net"} 0
node_filesystem_size_bytes{device="host:/path",fstype="nfs",mountpoint="/net/path"} 1.099511627776e+13
node_filesystem_size_bytes{device="host:/path2",fstype="nfs",mountpoint="/net/path2"} 1.078874406912e+12
```

The same command run from the command line seems to parse the flag correctly:
`collector=filesystem msg="Parsed flag --collector.filesystem.fs-types-exclude" flag=^(nfs|autofs)$`

```
 curl -s localhost:9100/metrics | grep -v ^# | grep -e autofs
# 
```

I think the config file needs to either not have the quotes around the value, or quotes around the entire flag key and value - so, something like this in the template:

`--collector.{{ name }}.{{ k }}={{ v }}`
or
`{{ ( '--collector.' + name + '.' + k + '=' + v  ) | quote }}`

I've only looked at this for node_exporter, but I guess this issue could be present in the other roles.

I've tested both these, and they both worked as expected.

**Comment by gardar** [comment]
#71
